services:
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8080"
    env_file: .env
    depends_on:
      - db
    command: ["./server"]
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  db_data: