services:
  backend:
    build: ./backend
    container_name: task_app_backend
    ports:
      - "8080:8080"
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_started
    command: ["./server"]
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: task_app_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: task_db
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"

volumes:
  db_data: