version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - bodyclose
    - unconvert

issues:
  max-same-issues: 5
  max-issues-per-linter: 20

run:
  timeout: 5m
  tests: true

severity:
  default: warning          # ← “デフォルト”を必ず定義
  rules:
    - linters:
        - revive
      severity: info
      