name: CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main", "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-lint-test:
    name: Build / Lint / Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Install oapi-codegen
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.5.0
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate code from OpenAPI
        run: make gen-oapi

      - name: Check generated code is up-to-date
        run: |
          git status --porcelain
          git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Test
        run: go test ./... -race -cover

  commitlint:
    name: Commit message lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js